app = "offroad-telegram-bot"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[env]
  TZ = "America/Sao_Paulo"

[processes]
  app = "python bot.py"

[deploy]
  strategy = "immediate"

[[vm]]
  size = "shared-cpu-1x"
  memory = 256

[mounts]
  source="data"
  destination="/data"
